name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auth_repository:
    path: packages/auth_repository
  user_repository:
    path: packages/user_repository
  intl: ^0.17.0
  meta: ^1.8.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  go_router: ^5.2.3
  http: ^0.13.5
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  font_awesome_flutter: ^10.3.0
  convex_bottom_bar: ^3.1.0+1
  yaml: ^3.1.1
  image_picker: ^0.8.6
  badges: ^2.0.3
  image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.2
  json_serializable: ^6.5.4



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo/
    - assets/configs/
