name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.11
  go_router: ^5.2.3
  hydrated_bloc: ^9.0.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  convex_bottom_bar: ^3.1.0+1
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auth_repository:
    path: packages/auth_repository

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo/
    - assets/configs/
