
services:
  auth: https://auth.app0.env0.luojm.com:9443/query
  user: https://user.luojm.com:9443
  contacts: https://contacts.luojm.com:9443
  message: https://message.luojm.com:9443

assets:
  logo:  assets/images/logo/logo.png

access_token_refresh_minutes: 180