
services:
  auth: https://auth.app0.env0.luojm.com:9443/query
  user: https://user.app0.env0.luojm.com:9443/query
  contacts: https://contacts.app0.env0.luojm.com:9443/query
  message: https://message.app0.env0.luojm.com:9443/query

assets:
  logo:  assets/images/logo/logo.png

access_token_refresh_minutes: 180